name: CD Pipeline

on:
  push:
    branches:
      - main
      - dev

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
  MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
  MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  MINIO_BUCKET_NAME: ${{ secrets.MINIO_BUCKET_NAME }}
  MINIO_CALENDAR_ACCESS_KEY: ${{ secrets.MINIO_CALENDAR_ACCESS_KEY }}
  MINIO_CALENDAR_SECRET_KEY: ${{ secrets.MINIO_CALENDAR_SECRET_KEY }}
  MINIO_CALENDAR_BUCKET_NAME: ${{ secrets.MINIO_CALENDAR_BUCKET_NAME }}
  MINIO_USE_SSL: ${{ secrets.MINIO_USE_SSL }}
  ENVIRONMENT: ${{ github.ref == 'refs/heads/dev' && 'dev' || 'prod' }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies (Optional)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log In to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            MONGO_URI=${{ env.MONGO_URI }}
            MINIO_ENDPOINT=${{ env.MINIO_ENDPOINT }}
            MINIO_ACCESS_KEY=${{ env.MINIO_ACCESS_KEY }}
            MINIO_SECRET_KEY=${{ env.MINIO_SECRET_KEY }}
            MINIO_BUCKET_NAME=${{ env.MINIO_BUCKET_NAME }}
            MINIO_CALENDAR_ACCESS_KEY=${{ env.MINIO_CALENDAR_ACCESS_KEY }}
            MINIO_CALENDAR_SECRET_KEY=${{ env.MINIO_CALENDAR_SECRET_KEY }}
            MINIO_CALENDAR_BUCKET_NAME=${{ env.MINIO_CALENDAR_BUCKET_NAME }}
            MINIO_USE_SSL=${{ env.MINIO_USE_SSL }}
            ENVIRONMENT=${{ env.ENVIRONMENT }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/python-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/python-backend:${{ github.sha }}

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/python-backend:latest
            docker stop python-backend || true
            docker rm python-backend || true
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              docker run -d --name python-backend --network itmomeet-network -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/python-backend:latest
            else
              docker run -d --name python-backend-dev -p 7000:8000 ${{ secrets.DOCKER_USERNAME }}/python-backend:latest
            fi
