name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
      - feat/*
  push:
    branches:
      - dev
      - feat/*

permissions:
  contents: read
  pull-requests: write
  checks: write

env:
  GITHUB_ACTIONS_CHECK_NAME: ""
  MONGO_URI: ${{ secrets.MONGO_URI }}
  MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
  MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
  MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  MINIO_BUCKET_NAME: ${{ secrets.MINIO_BUCKET_NAME }}
  MINIO_USE_SSL: ${{ secrets.MINIO_USE_SSL }}

jobs:
  setup-python:
    name: Set up Python and install dependencies
    runs-on: ubuntu-latest
    outputs:
      installed: ${{ steps.setup-completed.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        id: setup-completed
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Dependencies installed"

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: setup-python
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff linter
        run: |
          pip install ruff
          ruff check . --fix

      - name: Check if there are changes after linting
        run: git diff --exit-code || (echo "Linting issues detected!" && exit 1)

  test:
    name: unit_tests
    runs-on: ubuntu-latest
    needs: setup-python
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: pytest

  coverage:
    name: code_coverage
    runs-on: ubuntu-latest
    needs: [setup-python, test]
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run coverage
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Ensure test coverage is above 80%
        run: |
          coverage=$(grep '<coverage' coverage.xml | sed -E 's/.*line-rate="([^"]+)".*/\1/')
          coverage=$(echo "$coverage*100" | bc)
          if (( $(echo "$coverage < 80" | bc -l) )); then
            echo "Coverage is below 80%: $coverage%"
            exit 1
          else
            echo "Test coverage: $coverage%"
          fi

  check-pr:
    name: PR checks for merge
    runs-on: ubuntu-latest
    needs: [lint, test, coverage]
    if: github.event.pull_request.merged == false

    steps:
      - name: Verify PR checks
        run: echo "PR checks passed, ready to merge."
