name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
      - feat/*
  push:
    branches:
      - dev
      - feat/*

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  lint:
    name: ${{ github.event_name == 'pull_request' && 'Linting' || 'lint' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTIONS_CHECK_NAME: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff linter
        run: ruff check . --fix

      - name: Check if there are changes after linting
        run: git diff --exit-code || (echo "Linting issues detected!" && exit 1)

  test:
    name: ${{ github.event_name == 'pull_request' && 'unit_tests' || 'Unit Tests' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTIONS_CHECK_NAME: unit_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest

  coverage:
    name: ${{ github.event_name == 'pull_request' && 'code_coverage' || 'Coverage' }}
    runs-on: ubuntu-latest
    needs: test
    env:
      GITHUB_ACTIONS_CHECK_NAME: code_coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run coverage
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Ensure test coverage is above 80%
        run: |
          coverage=$(grep '<coverage' coverage.xml | sed -E 's/.*line-rate="([^"]+)".*/\1/')
          coverage=$(echo "$coverage*100" | bc)
          if (( $(echo "$coverage < 80" | bc -l) )); then
            echo "Coverage is below 80%: $coverage%"
            exit 1
          else
            echo "Test coverage: $coverage%"
          fi

  check-pr:
    name: PR checks for merge
    runs-on: ubuntu-latest
    needs: [lint, test, coverage]

    steps:
      - name: Verify PR checks
        if: github.event.pull_request.merged == false
        run: echo "PR checks passed, ready to merge."
